Areas/Admin/Controllers/AdminCustomerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Threading.Tasks;
using WebStore.Data;
using WebStore.Models;
using WebStore.Utility;

namespace WebStore.Areas.Admin.Controllers
{
    [Area(nameof(Admin))]
    [Authorize(Roles = SD.SuperAdminEndUser)]
    public class AdminCustomerController : Controller
    {
        private readonly ApplicationDbContext _db;

        public AdminCustomerController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> BanByIpOrMac(string id, bool isIp)
        {
            var userFromDB = await _db.ClientUsers.FindAsync(id);
            if (userFromDB is null)
                return NotFound();

            userFromDB.LockoutEnd = DateTime.Now.AddYears(1000);
            if (isIp)
            {
                IPBlackList iPBlackList = new()
                {
                    Address = userFromDB.IP,
                    UserId = userFromDB.Id
                };
                await _db.IPBlackLists.AddAsync(iPBlackList);
                TempData["SM"] = "User has been banned  by IP successfully!";
            }
            else
            {
                MacBlackList macBlackList = new()
                {
                    Address = userFromDB.UserMac,
                    UserId = userFromDB.Id
                };
                await _db.MacBlackLists.AddAsync(macBlackList);
                TempData["SM"] = "User has been banned by MAC successfully!";
            }
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        //public async Task<IActionResult> BanByMac(string id)
        //{
        //    var userFromDB = await _db.ClientUsers.FindAsync(id);
        //    if (userFromDB is null)
        //        return NotFound();
        //    userFromDB.LockoutEnd = DateTime.Now.AddYears(1000);

        //    await _db.SaveChangesAsync();

        //    return RedirectToAction("Index");
        //}

        public async Task<IActionResult> Index()
        {
            var userList = await _db.ClientUsers.ToListAsync();

            return View(userList);
        }
    }
}

Areas/Admin/Views/AdminCustomer/Index.cshtml
@model IEnumerable<WebStore.Models.ClientUser>
@{
    ViewData["Title"] = "Index";
}
@if (TempData["SM"] != null)
{
    <div class="row text-center">
        <div class="col-12 alert alert-success">
            @TempData["SM"]
        </div>
    </div>
}
<div class="row">
    <div class="col-6">
        <h2 class="text-info"> Users List</h2>
    </div>
</div>
<table class="table table-striped border">
    <thead>
        <tr class="table-info">
            <th>Name</th>
            <th>IP</th>
            <th>MAC</th>
            <th>Banned</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(x => item.UserName)
                </td>
                <td>
                    @Html.DisplayFor(x => item.IP)
                </td>
                <td>
                    @Html.DisplayFor(x => item.UserMac)
                </td>
                <td>
                    @if (item.LockoutEnd.HasValue)
                    {
                        @item.LockoutEnd.Value.ToString("dd.MM.yyyy");
                    }
                </td>
                @*<td><a asp-action=" BanByIpOrMac" asp-route-id="@item.Id" class="btn btn-danger">Ban IP</a></td>
                    <td><a asp-action="BanByMac" asp-route-id="@item.Id" class="btn btn-danger">Ban MAC</a></td>*@
                <td>@Html.ActionLink("Ban IP", "BanByIpOrMac", "AdminCustomer", new { id = @item.Id, isIp = true }, new { @class = "btn btn-danger" }) </td>
                <td>@Html.ActionLink("Ban MAC", "BanByIpOrMac", "AdminCustomer", new { id = @item.Id, isIp = false }, new { @class = "btn btn-danger" })</td>
                <td>@*TODO:Ban 3 days*@</td>
            </tr>
        }
    </tbody>
</table>