Models/Appointment.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebStore.Models
{
    public class Appointment
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter a name")]
        public string CustomerName { get; set; }

        [Required(ErrorMessage = "Please enter a surname")]
        public string CustomerSurname { get; set; }

        public string CustomerPhoneNumber { get; set; }
        public string CustomerEmail { get; set; }

        [Required(ErrorMessage = "Please enter the first address line")]
        [Display(Name = "Line 1")]
        public string Line1 { get; set; }

        [Required(ErrorMessage = "Please enter  a city name")]
        public string City { get; set; }

        public string Zip { get; set; }

        [Required(ErrorMessage = "Please enter a country name")]
        public string Country { get; set; }

        public DateTime AppointmentDay { get; set; }

        [NotMapped]
        public DateTime AppointmentTime { get; set; }

        public bool IsConfirmed { get; set; }
        public string SalesPersonID { get; set; }

        [ForeignKey(nameof(SalesPersonID))]
        public virtual ApplicationUser SalesPerson { get; set; }
    }
}

Models/ViewModel/AppointmentViewModel.cs
using System.Collections.Generic;

namespace WebStore.Models.ViewModel
{
    public class AppointmentViewModel
    {
        public List<Appointment> Appointments { get; set; }
        public PageInfo PaginationInfo { get; set; }
    }
}

Areas/Admin/Controllers/AppointmentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using WebStore.Data;
using WebStore.Models;
using WebStore.Models.ViewModel;
using WebStore.Utility;

namespace WebStore.Areas.Admin
{
    [Area(nameof(Admin))]
    public class AppointmentController : Controller
    {
        private readonly ApplicationDbContext _db;

        public AppointmentController(ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public AppointmentViewModel appointmentVM { get; set; } = new();

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var details = await GetDetailsAsync(id);
            //var products = (from p in _db.Products
            //                join a in _db.ProductsForAppointments
            //                on p.Id equals a.ProductId
            //                where a.AppointmentId == id
            //                select p).Include("ProductTypes") as IEnumerable<Product>;

            //AppointmentDetailsViewModel detailsVM = new()
            //{
            //    Appointment = await _db.Appointments.Include(x => x.SalesPerson).FirstOrDefaultAsync(x => x.Id == id),
            //    SalesPersons = await _db.ApplicationUsers.ToListAsync(),
            //    Products = products.ToList()
            //};
            //detailsVM.Appointment.AppointmentTime = detailsVM.Appointment.AppointmentTime
            //                                       .AddHours(detailsVM.Appointment.AppointmentDay.Hour)
            //                                       .AddMinutes(detailsVM.Appointment.AppointmentDay.Minute);

            return View(details);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePost(int? id)
        {
            if (id == null)
                return NotFound();

            Appointment appointmentFromDB = await _db.Appointments.FindAsync(id);

            if (appointmentFromDB != null)
            {
                _db.Appointments.Remove(appointmentFromDB);
                await _db.SaveChangesAsync();
                TempData["SM"] = $"Appointment  has been deleted successfully";
            }
            else
                TempData["SM"] = $"Appointment can not be deleted";

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();
            var details = await GetDetailsAsync(id);

            //var products = (from p in _db.Products
            //                join a in _db.ProductsForAppointments
            //                on p.Id equals a.ProductId
            //                where a.AppointmentId == id
            //                select p).Include("ProductTypes") as IEnumerable<Product>;

            //AppointmentDetailsViewModel detailsVM = new()
            //{
            //    Appointment = await _db.Appointments.Include(x => x.SalesPerson).FirstOrDefaultAsync(x => x.Id == id),
            //    SalesPersons = await _db.ApplicationUsers.ToListAsync(),
            //    Products = products.ToList()
            //};
            //detailsVM.Appointment.AppointmentTime = detailsVM.Appointment.AppointmentTime
            //                                       .AddHours(detailsVM.Appointment.AppointmentDay.Hour)
            //                                       .AddMinutes(detailsVM.Appointment.AppointmentDay.Minute);

            return View(details);
        }

        private async Task<AppointmentDetailsViewModel> GetDetailsAsync(int? id)
        {
            var products = (from p in _db.Products
                            join a in _db.ProductsForAppointments
                            on p.Id equals a.ProductId
                            where a.AppointmentId == id
                            select p).Include("ProductTypes") as IEnumerable<Product>;

            AppointmentDetailsViewModel detailsVM = new()
            {
                Appointment = await _db.Appointments.Include(x => x.SalesPerson).FirstOrDefaultAsync(x => x.Id == id),
                SalesPersons = await _db.ApplicationUsers.ToListAsync(),
                Products = products.ToList()
            };
            detailsVM.Appointment.AppointmentTime = detailsVM.Appointment.AppointmentTime
                                                   .AddHours(detailsVM.Appointment.AppointmentDay.Hour)
                                                   .AddMinutes(detailsVM.Appointment.AppointmentDay.Minute);
            return detailsVM;
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();
            var details = await GetDetailsAsync(id);

            //var products = (from p in _db.Products
            //                join a in _db.ProductsForAppointments
            //                on p.Id equals a.ProductId
            //                where a.AppointmentId == id
            //                select p).Include("ProductTypes") as IEnumerable<Product>;

            //AppointmentDetailsViewModel detailsVM = new()
            //{
            //    Appointment = await _db.Appointments.Include(x => x.SalesPerson).FirstOrDefaultAsync(x => x.Id == id),
            //    SalesPersons = await _db.ApplicationUsers.ToListAsync(),
            //    Products = products.ToList()
            //};
            //detailsVM.Appointment.AppointmentTime = detailsVM.Appointment.AppointmentTime
            //                                       .AddHours(detailsVM.Appointment.AppointmentDay.Hour)
            //                                       .AddMinutes(detailsVM.Appointment.AppointmentDay.Minute);

            return View(details);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(AppointmentDetailsViewModel detailsVM, int? id)
        {
            if (id != detailsVM.Appointment.Id)
                return NotFound();
            if (!ModelState.IsValid)
                return View(detailsVM);
            detailsVM.Appointment.AppointmentDay = detailsVM.Appointment.AppointmentDay
                                                            .AddHours(detailsVM.Appointment.AppointmentTime.Hour)
                                                            .AddMinutes(detailsVM.Appointment.AppointmentTime.Minute);

            var appointmentFromDB = await _db.Appointments.FindAsync(id);

            appointmentFromDB.CustomerName = detailsVM.Appointment.CustomerName;
            appointmentFromDB.CustomerEmail = detailsVM.Appointment.CustomerEmail;
            appointmentFromDB.CustomerPhoneNumber = detailsVM.Appointment.CustomerPhoneNumber;
            appointmentFromDB.AppointmentTime = detailsVM.Appointment.AppointmentTime;
            appointmentFromDB.AppointmentDay = detailsVM.Appointment.AppointmentDay;
            appointmentFromDB.IsConfirmed = detailsVM.Appointment.IsConfirmed;
            appointmentFromDB.CustomerSurname = detailsVM.Appointment.CustomerSurname;
            appointmentFromDB.City = detailsVM.Appointment.City;
            appointmentFromDB.Country = detailsVM.Appointment.Country;
            appointmentFromDB.Line1 = detailsVM.Appointment.Line1;
            appointmentFromDB.Zip = detailsVM.Appointment.Zip;

            if (User.IsInRole(SD.SuperAdminEndUser))
                appointmentFromDB.SalesPersonID = detailsVM.Appointment.SalesPersonID;

            await _db.SaveChangesAsync();
            TempData["SM"] = $"Appointment  has been edited successfully";

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Index(string searchKey, int productPage = 1)
        {
            // 1. Получаем объект типа ClaimsPrincipal
            var currentUser = this.User;

            // 2. Получаем объект идентификации юзера
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;

            // 3. Получаем доступ к объекту пользователя
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            StringBuilder param = new();
            param.Append("/Admin/Appointment?productPage=:");
            param.Append("&searchKey=");
            if (searchKey is not null)
                param.Append(searchKey);

            if (searchKey is null)
                appointmentVM.Appointments = await _db.Appointments.Include(x => x.SalesPerson).ToListAsync();
            else
            {
                appointmentVM.Appointments = await _db.Appointments.Include(x => x.SalesPerson)
                                                                   .Where(x => x.CustomerName.ToLower().Contains(searchKey.ToLower()) ||
                                                                          x.CustomerEmail.Contains(searchKey.ToLower()) ||
                                                                          x.CustomerPhoneNumber.Contains(searchKey.ToLower())).ToListAsync();
            }

            if (User.IsInRole(SD.AdminEndUser))
                appointmentVM.Appointments = appointmentVM.Appointments.Where(x => x.SalesPersonID == claim.Value).ToList();

            var count = appointmentVM.Appointments.Count;
            appointmentVM.Appointments = appointmentVM.Appointments.OrderBy(x => x.AppointmentDay)
                                                                   .Skip((productPage - 1) * SD.PageSize)
                                                                   .Take(SD.PageSize)
                                                                   .ToList();

Areas/Admin/Views/Appointment/Delete.cshtml
@model WebStore.Models.ViewModel.AppointmentDetailsViewModel
@using WebStore.Utility
@using WebStore.Extensions
@{
    ViewData["Title"] = "Delete";
}
@if (TempData["SM"] != null)
{
    <div class="row text-center">
        <div class="col-12 alert alert-success" role="alert">
            @TempData["SM"]
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    </div>
}
<h1 class="mt-1 text-info">Delete appointment</h1>
<form method="post" asp-action="Delete">

    <input type="hidden" asp-for="Appointment.Id" />
    <div class="p-4 border rounded row">
        <div class="row">
            <div class="col-12">
                <table class="table table-striped" width="100%">
                    <tbody>
                        <partial name="_AppointmentProductDetailsPartial" model="@Model.Products" />
                    </tbody>
                </table>
                <div class="row">
                    <div class="col-4">
                        <div class="form-group">
                            <label asp-for="Appointment.AppointmentDay"></label>
                            <input asp-for="Appointment.AppointmentDay" class="form-control" disabled />
                        </div>
                    </div>

                    <div class="col-4">
                        <div class="form-group">
                            <label asp-for="Appointment.CustomerName"></label>
                            <input asp-for="Appointment.CustomerName" class="form-control" disabled />
                        </div>
                    </div>

                    <div class="col-4">
                        <div class="form-group">
                            <label asp-for="Appointment.CustomerSurname"></label>
                            <input asp-for="Appointment.CustomerSurname" class="form-control" disabled />
                        </div>
                    </div>
                </div>


                <div class="row">
                    <div class="col-4">
                        <div class="form-group">
                            <label asp-for="Appointment.CustomerPhoneNumber"></label>
                            <input asp-for="Appointment.CustomerPhoneNumber" class="form-control" disabled />
                        </div>
                    </div>


                    <div class="col-4">
                        <div class="form-group">
                            <label asp-for="Appointment.CustomerEmail"></label>
                            <input asp-for="Appointment.CustomerEmail" class="form-control" disabled />
                        </div>
                    </div>

                    <div class="col-4">
                        <div class="form-group">
                            <label asp-for="Appointment.Line1"></label>
                            <input asp-for="Appointment.Line1" class="form-control" disabled />
                        </div>
                    </div>

                </div>


                <div class="row">
                    <div class="col-4">
                        <div class="form-group">
                            <label asp-for="Appointment.Zip"></label>
                            <input asp-for="Appointment.Zip" class="form-control" disabled />
                        </div>
                    </div>


                    <div class="col-4">
                        <div class="form-group">
                            <label asp-for="Appointment.City"></label>
                            <input asp-for="Appointment.City" class="form-control" disabled />
                        </div>
                    </div>


                    <div class="col-4">
                        <div class="form-group">
                            <label asp-for="Appointment.Country"></label>
                            <input asp-for="Appointment.Country" class="form-control" disabled />
                        </div>

                    </div>
                </div>

                <div class="row">
                    <div class="col-4">
                        <div class="form-group">
                            <label asp-for="Appointment.SalesPerson"></label>
                        </div>
                    </div>
                </div>
                @*<div class="row">*@                                        
                            @if (User.IsInRole(SD.SuperAdminEndUser))
                            {<div class="row">
                                    <div class="col-4">
                                        <div class="form-group">

                                            <select asp-for="Appointment.SalesPersonID" asp-items='Model.SalesPersons.ToSelectListItem(Model.Appointment.SalesPersonID)' class="form-control" disabled>
                                                <option value="">Select a SalesPerson</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            }
                            else if (User.IsInRole(SD.AdminEndUser))
                            {
                                <input type="hidden" asp-for="@Model.Appointment.SalesPersonID" />
                                <input asp-for="@Model.Appointment.SalesPerson.Name" class="form-control" disabled />
                            }
                            @*</div>*@                                       
                @*</div>*@

                <div class="row">
                    <div class="col-4">
                        <div class="form-group">
                            <label asp-for="Appointment.CustomerPhoneNumber"></label>
                            <input asp-for="Appointment.CustomerPhoneNumber" class="form-control" disabled />
                        </div>
                    </div>                  
                </div>

                <div class="row">
                    <div class="col-4">
                        <div class="form-group">
                            <label asp-for="Appointment.IsConfirmed"></label>
                            <input asp-for="Appointment.IsConfirmed" class="form-control" style="width: 15px" disabled />
                        </div>
                    </div>                   
                </div>

                @*<div class="col-6">
            <partial name="_AppointmentProductDetailsPartial" model="@Model.Products" />
        </div>*@
                <br />
            </div>
        </div>
        <div class="form-group">
            <input type="submit" asp-route-id="@Model.Appointment.Id" class="btn btn-danger" value="Delete" />
            <a class="btn btn-success" asp-action="Index">Back to list</a>
        </div>
    </div>
</form>

Areas/Admin/Views/Appointment/Details.cshtml
@model WebStore.Models.ViewModel.AppointmentDetailsViewModel
@using WebStore.Utility
@using WebStore.Extensions
@{
    ViewData["Title"] = "Details";
}
<h1 class="mt-1 text-info">Appointment Details</h1>
<div class="container border border-secondary rounded p-3">
    <div class="row">
        <div class="col-12">
            <table class="table table-striped" width="100%">
                <tbody>
                    <partial name="_AppointmentProductDetailsPartial" model="@Model.Products" />
                </tbody>
            </table>
            <div class="row">
                @*<div class="col-4 pb-3">*@
                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="Appointment.AppointmentDay"></label>
                        <input asp-for="Appointment.AppointmentDay" type="date" class="form-control" disabled />
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="Appointment.AppointmentTime"></label>
                        <input asp-for="Appointment.AppointmentTime" type="time" class="form-control" disabled />
                    </div>
                </div>

                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="Appointment.CustomerName"></label>
                        <input asp-for="Appointment.CustomerName" class="form-control" disabled />
                    </div>
                </div>
                @*</div>*@
            </div>
            <div class="row">
                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="Appointment.CustomerPhoneNumber"></label>
                        <input asp-for="Appointment.CustomerPhoneNumber" class="form-control" disabled />
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="Appointment.CustomerEmail"></label>
                        <input asp-for="Appointment.CustomerEmail" class="form-control" disabled />
                    </div>
                </div>
            </div>

            @*<div class="row">*@
            @*<div class="col-4">
                    <div class="form-group">
                        <label asp-for="Appointment.CustomerEmail"></label>
                        <input asp-for="Appointment.CustomerEmail" class="form-control" disabled />
                    </div>
                </div>*@
            @*</div>*@

            <div class="row">
                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="Appointment.SalesPerson"></label>
                    </div>
                </div>
            </div>
            @if (User.IsInRole(SD.SuperAdminEndUser))
            {
                <div class="row">
                    <div class="col-4">
                        <div class="form-group">

                            <select asp-for="Appointment.SalesPersonID" asp-items='Model.SalesPersons.ToSelectListItem(Model.Appointment.SalesPersonID)' class="form-control" disabled>
                                <option value="">Select a SalesPerson</option>
                            </select>
                        </div>
                    </div>
                </div>
            }
            else if (User.IsInRole(SD.AdminEndUser))
            {
                <div class="row">
                    <div class="col-4">
                        <div class="form-group">
                            <input type="hidden" asp-for="Appointment.SalesPersonID" />
                            <input asp-for="Appointment.SalesPerson.Name" class="form-control" disabled />
                        </div>
                    </div>
                </div>
            }

            <div class="row">
                <div class="col-4">
                    <div class="form-group">
                        <label asp-for="Appointment.IsConfirmed"></label>
                        <input asp-for="Appointment.IsConfirmed" class="form-control" style="width: 15px" disabled />
                    </div>
                </div>
            </div>
        </div>
        @*<div class="col-6">
                <partial name="_AppointmentProductDetailsPartial" model="@Model.Products" />
            </div>*@
    </div>
    <div class="form-group">
        <a asp-action="Index" class="btn btn-success">Back to List</a>
    </div>
</div>

Areas/Admin/Views/Appointment/Edit.cshtml
@model WebStore.Models.ViewModel.AppointmentDetailsViewModel
@using WebStore.Extensions
@using WebStore.Utility
@{
    ViewData["Title"] = "Edit";
}
@if (TempData["SM"] != null)
{
    <div class="row text-center">
        <div class="col-12 alert alert-success" role="alert">
            @TempData["SM"]
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    </div>
}

<h2 class="text-info">Edit Appointment</h2>
<form method="post" enctype="multipart/form-data">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="container border border-secondary rounded p-3">

        <input type="hidden" asp-for="@Model.Appointment.Id" />

        <div class="row">
            <div class="col-12">
                <table class="table table-striped" width="100%">
                    <tbody>
                        <partial name="_AppointmentProductDetailsPartial" model="@Model.Products" />
                        @*@foreach (var item in Model.Products)
        {
            <tr class="text-center p-5">
                <td class="align-middle">
                    <a asp-area="Admin" asp-controller="Appointment" asp-action="Edit" asp-route-id="@item.Id">
                        <img src="@item.Image" class="image-product-style" />
                    </a>
                </td>
                <td class="align-middle">
                    @Html.DisplayFor(x => item.Name)
                </td>
                <td class="align-middle">
                    @String.Format("{0:C}", item.Price)
                </td>
                <td class="align-middle">
                    @Html.DisplayFor(x => item.ShadeColor)
                </td>
                <td class="align-middle">
                    @Html.DisplayFor(x => item.ProductTypes.Name)
                </td>
            </tr>
        }*@
                    </tbody>
                    @*<input asp-for="Appointment.AppointmentDay" type="date" class="form-control" />*@
                </table>
                    <div class="row">
                        <div class="col-4 pb-3">
                            <div class="form-group">
                                <label asp-for="Appointment.AppointmentTime"></label>
                                <input asp-for="Appointment.AppointmentTime" type="time" class="form-control" />
                            </div>
                        </div>

                    <div class="col-4">
                        <div class="form-group">
                            <label asp-for="Appointment.CustomerName"></label>
                            <input asp-for="Appointment.CustomerName" class="form-control" />
                            <span asp-validation-for="Appointment.CustomerName" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="col-4">
                        <div class="form-group">
                            <label asp-for="Appointment.CustomerSurname"></label>
                            <input asp-for="Appointment.CustomerSurname" class="form-control" />
                            <span asp-validation-for="Appointment.CustomerName" class="text-danger"></span>
                        </div>
                    </div>
                    </div>

                    <div class="row">
                        <div class="col-4">
                            <div class="form-group">
                                <label asp-for="Appointment.Line1"></label>
                                <input asp-for="Appointment.Line1" class="form-control" />
                                <span asp-validation-for="Appointment.Line1" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="form-group">
                                <label asp-for="Appointment.Zip"></label>
                                <input asp-for="Appointment.Zip" class="form-control" />
                            </div>
                        </div>
                    </div>

                    <div class="row ">
                        <div class="col-4">
                            <div class="form-group">
                                <label asp-for="Appointment.City"></label>
                                <input asp-for="Appointment.City" class="form-control" />
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="form-group">
                                <label asp-for="Appointment.Country"></label>
                                <input asp-for="Appointment.Country" class="form-control" />
                            </div>
                        </div>
                    </div>

                    @*<div class="row">*@
            <div class="row">
                <div class="col-4">
                    <label asp-for="Appointment.SalesPerson"></label>
                </div>
            </div>
                        @if (User.IsInRole(SD.SuperAdminEndUser))
                        {
                            <div class="row">
                                <div class="col-4">
                                    <select asp-for="@Model.Appointment.SalesPersonID" asp-items='@Model.SalesPersons.ToSelectListItem(Model.Appointment.SalesPersonID)' class="form-control">
                                        <option value="">Select a SalesPerson</option>
                                    </select>
                                </div>
                            </div>
                        }
                        else if (User.IsInRole(SD.AdminEndUser))
                        {
                            <div class="col-8">
                                <input type="hidden" asp-for="@Model.Appointment.SalesPersonID" />
                                <input asp-for="@Model.Appointment.SalesPerson.Name" class="form-control" disabled />
                            </div>
                        }
                    @*</div>*@

                    <div class="row">
                        <div class="col-4">
                            <div class="form-group">
                                <label asp-for="Appointment.IsConfirmed"></label>
                                <input asp-for="Appointment.IsConfirmed" class="form-control" style="width: 15px" />
                            </div>
                        </div>
                    </div>
            </div>
        </div>
        @*<div class="col-6">
            <partial name="_AppointmentProductDetailsPartial" model="@Model.Products" />
        </div>*@

        <div class="form-group">
            <input type="submit" class="btn btn-primary" asp-route-id="@Model.Appointment.Id" value="Edit" />
            <a asp-action="Index" class="btn btn-success">Back to List</a>
        </div>
    </div>
</form>

@section Scripts
{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}